#Tugas 1

In [87]:
import pandas as pd
import numpy as np

In [88]:
# Create dataset from Google Drive
dataset_url = "https://raw.githubusercontent.com/AISPUBLISHING/Book-Statistics-Beginners-Python/master/baseball_stats.csv"
df = pd.read_csv(dataset_url, index_col='Team')

In [89]:
df

,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG
Team,,,,,,,,,,,,,,
ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415
ATL,NL,2012,700,600,94,0.320,0.389,0.247,1,4.0,5.0,162,0.306,0.378
BAL,AL,2012,712,705,93,0.311,0.417,0.247,1,5.0,4.0,162,0.315,0.403
BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428
CHC,NL,2012,613,759,61,0.302,0.378,0.240,0,NaN,NaN,162,0.335,0.424
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PHI,NL,1962,705,759,81,0.330,0.390,0.260,0,NaN,NaN,161,NaN,NaN
PIT,NL,1962,706,626,93,0.321,0.394,0.268,0,NaN,NaN,161,NaN,NaN
SFG,NL,1962,878,690,103,0.341,0.441,0.278,1,1.0,2.0,165,NaN,NaN
STL,NL,1962,774,664,84,0.335,0.394,0.271,0,NaN,NaN,163,NaN,NaN
WSA,AL,1962,599,716,60,0.308,0.373,0.250,0,NaN,NaN,162,NaN,NaN

In [90]:
# Show dataset shape
number_of_columns = df.shape[1]

In [91]:
# Show all columns for dataset
pd.set_option('display.max_columns', number_of_columns)
pd.set_option('display.max_rows', number_of_columns)

In [92]:
# Show all columns from dataframe
df.columns

Index(['League', 'Year', 'RS', 'RA', 'W', 'OBP', 'SLG', 'BA', 'Playoffs',
       'RankSeason', 'RankPlayoffs', 'G', 'OOBP', 'OSLG'],
      dtype='object')

In [93]:
df[["Year","League", "Playoffs"]].head(5)

      Year League  Playoffs
Team
ARI   2012     NL         0
ATL   2012     NL         1
BAL   2012     AL         1
BOS   2012     AL         0
CHC   2012     NL         0

In [94]:
# league code
code_league_for_cherbourg = "NL"
code_league_for_southampton = "AL"

# binary value
value_of_one = 1
value_of_zero = 0

def change_code_league_to_biner(leagueed):
    return value_of_one if leagueed == code_league_for_southampton else value_of_zero

In [95]:
# Update all values of 'leagueed' series
df["leagueed"] = df["leagueed"].apply(change_code_league_to_biner)

KeyError: ignored